ca:
  # Name of this CA
  name: tlsca

affiliations:
   org1:
      - department1
      - department2
csr:
   cn: tlsca.org2.example.com
   keyrequest:
     algo: ecdsa
     size: 256
   names:
      - C: SG
        ST: Singapore
        L: Singapore
        O: org2.example.com
        OU:
   hosts:
     - tlsca.org2.example.com
     - localhost
   ca:
      expiry: 131400h
      pathlength: 1